// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin/email/cleanup": {
            "post": {
                "description": "清理数据库中已过期的验证码记录（定时任务调用）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理"
                ],
                "summary": "清理过期验证码",
                "responses": {
                    "200": {
                        "description": "清理完成",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "清理失败",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/admin/email/stats": {
            "get": {
                "description": "获取邮箱验证码发送统计信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理"
                ],
                "summary": "获取邮箱服务统计",
                "responses": {
                    "200": {
                        "description": "统计信息",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/admin/email/test-connection": {
            "get": {
                "description": "测试邮箱SMTP服务器连接状态（仅用于调试）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理"
                ],
                "summary": "测试SMTP连接",
                "responses": {
                    "200": {
                        "description": "SMTP连接正常",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "SMTP连接失败",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "example": "{\"identifier\":\"1001\",\"password\":\"password123\"}",
                        "description": "登录参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "认证失败",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用户登出，使当前令牌失效。令牌需置于Header中：Authorization: Bearer \u003ctoken\u003e（bearer和token中间有空格）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户登出",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.LogoutResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前已认证登录用户的详细信息，需要有效的JWT令牌。令牌需置于Header中：Authorization: Bearer \u003ctoken\u003e",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "获取当前用户个人信息",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功获取用户信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误或用户标识缺失",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "未提供有效的认证令牌",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "用户不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误或用户标识格式错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/auth/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "example": "{\"id\":1001,\"username\":\"张三\",\"email\":\"user@example.com\",\"password\":\"password123\",\"code\":\"123456\"}",
                        "description": "注册参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "注册成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "用户已存在",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/email/send-verification": {
            "post": {
                "description": "向指定邮箱发送6位数字验证码，支持多种业务场景",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "邮箱验证"
                ],
                "summary": "发送邮箱验证码",
                "parameters": [
                    {
                        "description": "发送验证码请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.SendVerificationCodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "验证码发送成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "429": {
                        "description": "请求过于频繁",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/email/verify": {
            "post": {
                "description": "验证邮箱和验证码是否匹配且有效，支持多种业务场景",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "邮箱验证"
                ],
                "summary": "验证邮箱验证码",
                "parameters": [
                    {
                        "description": "验证验证码请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.VerifyCodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "验证码验证成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "验证码无效或已过期",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.SendVerificationCodeRequest": {
            "type": "object",
            "required": [
                "business",
                "email"
            ],
            "properties": {
                "business": {
                    "description": "业务类型: register, reset_password, change_email, join_org",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱地址",
                    "type": "string"
                }
            }
        },
        "handlers.VerifyCodeRequest": {
            "type": "object",
            "required": [
                "business",
                "code",
                "email"
            ],
            "properties": {
                "business": {
                    "description": "业务类型",
                    "type": "string"
                },
                "code": {
                    "description": "6位验证码",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱地址",
                    "type": "string"
                }
            }
        },
        "services.LogoutResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Team Task Hub API",
	Description:      "团队任务管理平台API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
