// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin/email/cleanup": {
            "post": {
                "description": "清理数据库中已过期的验证码记录（定时任务调用）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理"
                ],
                "summary": "清理过期验证码",
                "responses": {
                    "200": {
                        "description": "清理完成",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "清理失败",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/admin/email/stats": {
            "get": {
                "description": "获取邮箱验证码发送统计信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理"
                ],
                "summary": "获取邮箱服务统计",
                "responses": {
                    "200": {
                        "description": "统计信息",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/admin/email/test-connection": {
            "get": {
                "description": "测试邮箱SMTP服务器连接状态（仅用于调试）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理"
                ],
                "summary": "测试SMTP连接",
                "responses": {
                    "200": {
                        "description": "SMTP连接正常",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "SMTP连接失败",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/auth/change_avatar": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "更新用户头像",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "example": "{\"avatar_url\": \"https://example.com/new-avatar.jpg\"}",
                        "description": "更新头像参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功\" example({\"success\": true, \"message\": \"头像更新成功\"})",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "参数错误\" example({\"success\": false, \"message\": \"请求参数格式错误\"})",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/auth/change_email": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "更新用户邮箱",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "example": "{\"new_email\": \"new@example.com\", \"old_email_code\": \"123456\", \"new_email_code\": \"654321\"}",
                        "description": "更新邮箱参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功\" example({\"success\": true, \"message\": \"邮箱更新成功\"})",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "参数错误\" example({\"success\": false, \"message\": \"请求参数格式错误\"})",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "邮箱冲突\" example({\"success\": false, \"message\": \"邮箱已被使用\"})",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/auth/change_password": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "更新用户密码",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "example": "{\"email\": \"user@example.com\", \"code\": \"123456\", \"new_password\": \"newpassword123\"}",
                        "description": "更新密码参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功\" example({\"success\": true, \"message\": \"密码更新成功\"})",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "参数错误\" example({\"success\": false, \"message\": \"请求参数格式错误\"})",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/auth/change_userName": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "更新用户名",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "example": "{\"username\": \"新用户名\"}",
                        "description": "更新用户名参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功\" example({\"success\": true, \"message\": \"用户名更新成功\"})",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "参数错误\" example({\"success\": false, \"message\": \"请求参数格式错误\"})",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "用户名冲突\" example({\"success\": false, \"message\": \"用户名已被占用\"})",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "example": "{\"identifier\":\"1001\",\"password\":\"password123\"}",
                        "description": "登录参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "认证失败",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用户登出，使当前令牌失效。令牌需置于Header中：Authorization: Bearer \u003ctoken\u003e（bearer和token中间有空格）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户登出",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/services.LogoutResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前已认证登录用户的详细信息，需要有效的JWT令牌。令牌需置于Header中：Authorization: Bearer \u003ctoken\u003e",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "获取当前用户个人信息",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功\" example({\"success\": true, \"message\": \"获取用户信息成功\", \"data\": {\"id\": 1001, \"username\": \"张三\", \"email\": \"user@example.com\", \"avatar_url\": \"https://example.com/avatar.jpg\"}})",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "请求参数错误或用户标识缺失",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "未提供有效的认证令牌",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "用户不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误或用户标识格式错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/auth/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "example": "{\"id\":1001,\"username\":\"张三\",\"email\":\"user@example.com\",\"password\":\"password123\",\"code\":\"123456\"}",
                        "description": "注册参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "注册成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "用户已存在",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/email/send-verification": {
            "post": {
                "description": "向指定邮箱发送6位数字验证码，支持多种业务场景，\"register\",\"change_email_old\",\"change_email_new\",\"change_password\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "邮箱验证"
                ],
                "summary": "发送邮箱验证码",
                "parameters": [
                    {
                        "description": "发送验证码请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.SendVerificationCodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "验证码发送成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "429": {
                        "description": "请求过于频繁",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/email/verify": {
            "post": {
                "description": "验证邮箱和验证码是否匹配且有效，支持多种业务场景",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "邮箱验证"
                ],
                "summary": "验证邮箱验证码",
                "parameters": [
                    {
                        "description": "验证验证码请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.VerifyCodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "验证码验证成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "验证码无效或已过期",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/todos/UpdateTodos": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "为有生育能力的过期待办自动创建下一代实例",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "待办事项"
                ],
                "summary": "续期过期待办",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "续期成功\" example({\"success\": true, \"message\": \"续期完成: 成功 3, 跳过 1, 失败 0\"})",
                        "schema": {
                            "$ref": "#/definitions/handlers.RenewTodoResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误\" example({\"success\": false, \"message\": \"用户未认证\"})",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "系统内部错误\" example({\"success\": false, \"message\": \"续期操作失败: 数据库连接错误\"})",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/todos/cancel": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据待办的具体信息将其状态改为已取消",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "待办事项"
                ],
                "summary": "取消待办事项",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "取消待办请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CancelTodoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取消成功\" example({\"success\": true, \"message\": \"待办已成功取消\"})",
                        "schema": {
                            "$ref": "#/definitions/handlers.CancelTodoResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误\" example({\"success\": false, \"message\": \"请求参数格式错误\"})",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "未授权\" example({\"success\": false, \"message\": \"用户未认证\"})",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "系统内部错误\" example({\"success\": false, \"message\": \"取消待办失败: 数据库错误\"})",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/todos/cancel-with-children": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据待办标题和描述取消父待办及其所有子待办（使用事务确保一致性）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "待办事项"
                ],
                "summary": "取消待办及其所有子待办",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "取消待办请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CancelTodoAndChildrenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取消成功\" example({\"success\": true, \"message\": \"待办及其子待办已成功取消\"})",
                        "schema": {
                            "$ref": "#/definitions/handlers.CancelTodoResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误\" example({\"success\": false, \"message\": \"请求参数格式错误\"})",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "未找到待办\" example({\"success\": false, \"message\": \"未找到匹配的待办事项\"})",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "系统内部错误\" example({\"success\": false, \"message\": \"取消操作失败: 数据库错误\"})",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/todos/coming-endTodos": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "查询在未来七天内会结束的所有待办事项",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "待办查询"
                ],
                "summary": "获取未来七天会结束的待办事项",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功\" example({\"success\": true, \"message\": \"查询成功\", \"todos\": [...], \"count\": 3})",
                        "schema": {
                            "$ref": "#/definitions/handlers.TodoListResponse"
                        }
                    },
                    "401": {
                        "description": "未授权\" example({\"success\": false, \"message\": \"用户未认证\"})",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "系统内部错误\" example({\"success\": false, \"message\": \"查询未来七天结束的待办失败: 数据库错误\"})",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/todos/coming-startTodos": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "查询在未来七天内会开始的所有待办事项",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "待办查询"
                ],
                "summary": "获取未来七天会开始的待办事项",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功\" example({\"success\": true, \"message\": \"查询成功\", \"todos\": [...], \"count\": 5})",
                        "schema": {
                            "$ref": "#/definitions/handlers.TodoListResponse"
                        }
                    },
                    "401": {
                        "description": "未授权\" example({\"success\": false, \"message\": \"用户未认证\"})",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "系统内部错误\" example({\"success\": false, \"message\": \"查询未来七天开始的待办失败: 数据库错误\"})",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/todos/complete": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据待办的具体信息将其状态改为已完成，并自动记录完成时间",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "待办事项"
                ],
                "summary": "完成待办事项",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "完成待办请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CompleteTodoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "完成成功\" example({\"success\": true, \"message\": \"待办已完成于 2024-01-15 14:30\"})",
                        "schema": {
                            "$ref": "#/definitions/handlers.CompleteTodoResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误\" example({\"success\": false, \"message\": \"标题和内容不能为空\"})",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "系统内部错误\" example({\"success\": false, \"message\": \"完成待办失败: 数据库错误\"})",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/todos/completed_todo": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "查询在指定日期完成的所有待办事项",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "待办查询"
                ],
                "summary": "获取指定日期完成的待办事项",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"2024-01-15\"",
                        "description": "查询日期",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功\" example({\"success\": true, \"message\": \"查询成功\", \"date\": \"2024-01-15\", \"todos\": [...], \"count\": 3})",
                        "schema": {
                            "$ref": "#/definitions/handlers.CompletedTodoResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误\" example({\"success\": false, \"message\": \"日期参数不能为空\"})",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "未授权\" example({\"success\": false, \"message\": \"用户未认证\"})",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "系统内部错误\" example({\"success\": false, \"message\": \"查询已完成待办失败: 数据库错误\"})",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/todos/createTodo": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建普通待办或重复待办事项。重复待办会根据规则及ChildDates生成子实例。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "待办事项"
                ],
                "summary": "创建待办事项",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "创建待办请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/services.CreateTodoRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "创建成功\" example({\"success\": true, \"message\": \"待办创建成功\", \"created_at\": \"2024-01-15T10:30:00Z\"})",
                        "schema": {
                            "$ref": "#/definitions/services.CreateTodoResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误\" example({\"success\": false, \"message\": \"标题不能为空\"})",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "系统内部错误\" example({\"success\": false, \"message\": \"创建待办失败: 数据库连接错误\"})",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/todos/todayTodos": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "查询与今天时间段有交集的所有未完成待办事项",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "待办查询"
                ],
                "summary": "获取今日待办事项",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功\" example({\"success\": true, \"message\": \"查询成功\", \"todos\": [...], \"count\": 5})",
                        "schema": {
                            "$ref": "#/definitions/handlers.TodoListResponse"
                        }
                    },
                    "401": {
                        "description": "未授权\" example({\"success\": false, \"message\": \"用户未认证\"})",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "系统内部错误\" example({\"success\": false, \"message\": \"查询今日待办失败: 数据库错误\"})",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.CancelTodoAndChildrenRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "项目进度讨论"
                },
                "title": {
                    "type": "string",
                    "example": "每周团队会议"
                }
            }
        },
        "handlers.CancelTodoRequest": {
            "type": "object",
            "required": [
                "end_time",
                "start_time",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "项目进度讨论"
                },
                "end_time": {
                    "type": "string",
                    "example": "2024-01-15T15:00:00Z"
                },
                "start_time": {
                    "type": "string",
                    "example": "2024-01-15T14:00:00Z"
                },
                "title": {
                    "type": "string",
                    "example": "团队会议"
                }
            }
        },
        "handlers.CancelTodoResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "handlers.CompleteTodoRequest": {
            "type": "object",
            "required": [
                "description",
                "end_time",
                "start_time",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "项目进度讨论"
                },
                "end_time": {
                    "type": "string",
                    "example": "2024-01-15T15:00:00Z"
                },
                "start_time": {
                    "type": "string",
                    "example": "2024-01-15T14:00:00Z"
                },
                "title": {
                    "type": "string",
                    "example": "团队会议"
                }
            }
        },
        "handlers.CompleteTodoResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "handlers.CompletedTodoResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "todos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Todo"
                    }
                }
            }
        },
        "handlers.RenewTodoResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "handlers.SendVerificationCodeRequest": {
            "type": "object",
            "required": [
                "business",
                "email"
            ],
            "properties": {
                "business": {
                    "description": "业务类型: register, reset_password, change_email, join_org",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱地址",
                    "type": "string"
                }
            }
        },
        "handlers.TodoListResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "todos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Todo"
                    }
                }
            }
        },
        "handlers.VerifyCodeRequest": {
            "type": "object",
            "required": [
                "business",
                "code",
                "email"
            ],
            "properties": {
                "business": {
                    "description": "业务类型",
                    "type": "string"
                },
                "code": {
                    "description": "6位验证码",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱地址",
                    "type": "string"
                }
            }
        },
        "models.Todo": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "completed_at": {
                    "type": "string"
                },
                "creator_organ_id": {
                    "type": "integer"
                },
                "creator_user_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "has_children": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "parent_id": {
                    "description": "父子关系",
                    "type": "integer"
                },
                "repeat_end_date": {
                    "type": "string"
                },
                "repeat_interval": {
                    "type": "integer"
                },
                "repeat_type": {
                    "description": "重复规则",
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "urgency": {
                    "type": "string"
                }
            }
        },
        "services.CreateTodoRequest": {
            "type": "object",
            "required": [
                "end_time",
                "start_time",
                "title"
            ],
            "properties": {
                "category": {
                    "type": "string",
                    "default": "personal",
                    "enum": [
                        "work",
                        "study",
                        "fun",
                        "personal"
                    ]
                },
                "child_dates": {
                    "description": "子待办日期数组",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "repeat_end_date": {
                    "type": "string"
                },
                "repeat_interval": {
                    "type": "integer",
                    "default": 1
                },
                "repeat_type": {
                    "description": "重复规则",
                    "type": "string",
                    "default": "none",
                    "enum": [
                        "none",
                        "daily",
                        "weekly",
                        "monthly"
                    ]
                },
                "start_time": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "urgency": {
                    "type": "string",
                    "default": "medium",
                    "enum": [
                        "low",
                        "medium",
                        "high"
                    ]
                }
            }
        },
        "services.CreateTodoResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "services.LogoutResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Team Task Hub API",
	Description:      "团队任务管理平台API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
